dispatch_lang:
    path:     /
    controller: App\Controller\DefaultController::dispatch


controllers:
    resource: ../../src/Controller/
    type: annotation
    prefix: /{_locale}
    requirements:
        _locale: fr|es|en